### ISSUE TITLE
stuck on "cool you reviewed already 37 responses" in Level 1 moderation screen

### ISSUE THREAD

**Issue by rtanglao** [mozilla/sumo-playstore-campaign#56] opened 2018-06-08 03:56 UTC
see screenshot:

![screenshot-2018-6-7 thank you sumo](https://user-images.githubusercontent.com/45195/41138303-4a2f0268-6a95-11e8-94af-ed6fc70b9958.png)

**Comment by MichaelKohler** [comment] 2018-06-08 09:43
Duplicate of #37

**Closed as completed** 2018-06-08 09:43 UTC
