### ISSUE TITLE
Response counter doens't work (moderation)

### ISSUE THREAD

**Issue by LucyeoH-zz** [mozilla/sumo-playstore-campaign#51] opened 2018-06-06 15:21 UTC
After I've moderated several responses it still shows that I've only done 1. 

<img width="575" alt="screen shot 2018-06-06 at 11 19 04 am" src="https://user-images.githubusercontent.com/8070833/41047981-bcda0436-697b-11e8-98e9-fd24382a7341.png">

**Comment by MichaelKohler** [comment] 2018-06-06 15:55
Dupe of #35

**Comment by MichaelKohler** [comment] 2018-06-06 15:55
#37 that is

**Closed as completed by MichaelKohler** 2018-06-06 15:55 UTC
